<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All IssuesDoctor was not available.I_708e25</name>
   <tag></tag>
   <elementGuidId>4cd52f8d-501d-4c96-912c-d1074eb01014</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#entityFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='entityFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Issue:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5fd87bbc-37ae-4c0e-bc5d-bad55b147e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>entityFilter</value>
      <webElementGuid>270fd6ea-ee82-4e0a-8b07-046c903bf0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-400 px-2 py-1 text-sm max-w-[150px] rounded-[5px] truncate</value>
      <webElementGuid>aa0e8dfa-0d66-4cd1-b64a-070cced2cd0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All IssuesDoctor was not available.Improper services reported.Medicines were not provided.Service fee was unclear.</value>
      <webElementGuid>2b81cc3a-087c-4089-845f-082080d26e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entityFilter&quot;)</value>
      <webElementGuid>536dbacd-ec57-47e5-b0b8-c7662a6fee6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='entityFilter']</value>
      <webElementGuid>c80b1674-fdce-4c4a-ad2c-a0eebe9c4647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div[3]/select</value>
      <webElementGuid>228a3fa6-933e-4f2a-862e-eb5ce1e406ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issue:'])[1]/following::select[1]</value>
      <webElementGuid>6f0e7d5f-8080-4482-add4-9fd990a33872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaign:'])[1]/following::select[2]</value>
      <webElementGuid>fe915106-bcf7-4e7d-82fc-d83ed6ef973b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By:'])[1]/preceding::select[1]</value>
      <webElementGuid>5503776c-153e-429e-a84f-1740fef3211c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Date:'])[1]/preceding::select[2]</value>
      <webElementGuid>090d8ec7-f579-4e12-8285-f32661adeaaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>236604d0-3fab-484d-a9fd-94cd96e2ae51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'entityFilter' and (text() = 'All IssuesDoctor was not available.Improper services reported.Medicines were not provided.Service fee was unclear.' or . = 'All IssuesDoctor was not available.Improper services reported.Medicines were not provided.Service fee was unclear.')]</value>
      <webElementGuid>ae6ef002-e0f8-4200-9d56-1cbd99917690</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
