<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome_w-full bg-gray-50 border bord_29b4f0_1_2</name>
   <tag></tag>
   <elementGuidId>0729dbc3-d885-4c1d-9439-b86066e0d31e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Username&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2dd2d05f-9517-4eb1-9383-ec133e540920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4dff3b7-cc31-4be3-b5ca-239a572b0ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>faf20978-3ff5-4237-ab3c-ea4f42037c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full bg-gray-50 border border-gray-300 rounded-lg pl-10 pr-4 py-3 text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 focus:bg-white transition duration-200 shadow-sm</value>
      <webElementGuid>83bd4026-1cfd-4dae-8bd8-1bdd74526847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Collector</value>
      <webElementGuid>c0f55c80-fd55-4393-9982-8036ff76a24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;text-text&quot;]/div[@class=&quot;min-h-screen text-primary relative overflow-hidden flex items-center justify-center p-4 bg-gray-50&quot;]/div[@class=&quot;container mx-auto relative z-10 h-max&quot;]/div[@class=&quot;flex flex-col md:flex-row max-w-4xl mx-auto bg-white shadow-2xl shadow-secondary rounded-xl overflow-hidden&quot;]/div[@class=&quot;w-full md:w-1/2 p-4 md:p-10&quot;]/div[1]/form[@class=&quot;space-y-5&quot;]/div[@class=&quot;relative group&quot;]/input[@class=&quot;w-full bg-gray-50 border border-gray-300 rounded-lg pl-10 pr-4 py-3 text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 focus:bg-white transition duration-200 shadow-sm&quot;]</value>
      <webElementGuid>04a5af50-3540-407d-8973-39d8112f7cac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Collector']</value>
      <webElementGuid>a3bc7ccc-328a-4106-97c9-63958ddf5b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div/div[2]/div/form/div/input</value>
      <webElementGuid>abf57c1b-1f95-4f21-91ef-c81b7d39ea9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>70930db1-7a6c-49ac-a5d2-bd959446695d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Username']</value>
      <webElementGuid>10c4933d-162c-4823-905f-e27d0a00afb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
