<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome_w-full bg-gray-50 border bord_c3e347</name>
   <tag></tag>
   <elementGuidId>8922d77b-2c13-4de8-ad65-60a79ed99fc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6b6933d-4506-4692-bd70-d3399082c0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>54871269-c745-441b-b353-db3471dfe111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>4229c7e9-7bdd-47d2-8f45-2e380de0fde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full bg-gray-50 border border-gray-300 rounded-lg pl-10 pr-10 py-3 text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 focus:bg-white transition duration-200 shadow-sm</value>
      <webElementGuid>8d7e17e0-3b6c-4536-88c2-f1f2792f1cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>94a9a3ab-36fe-46cc-bac2-c30a6952c33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;text-text&quot;]/div[@class=&quot;min-h-screen text-primary relative overflow-hidden flex items-center justify-center p-4 bg-gray-50&quot;]/div[@class=&quot;container mx-auto relative z-10 h-max&quot;]/div[@class=&quot;flex flex-col md:flex-row max-w-4xl mx-auto bg-white shadow-2xl shadow-secondary rounded-xl overflow-hidden&quot;]/div[@class=&quot;w-full md:w-1/2 p-4 md:p-10&quot;]/div[1]/form[@class=&quot;space-y-5&quot;]/div[@class=&quot;relative group&quot;]/input[@class=&quot;w-full bg-gray-50 border border-gray-300 rounded-lg pl-10 pr-10 py-3 text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 focus:bg-white transition duration-200 shadow-sm&quot;]</value>
      <webElementGuid>bbc991f5-6de2-4a20-ad2f-068ed4848a48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='a']</value>
      <webElementGuid>c88adab5-d867-49f3-b84d-acf58d174ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div/div[2]/div/form/div[2]/input</value>
      <webElementGuid>a33e1233-4eec-4f5d-b94b-0b50ae288aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2836afc0-3161-42dd-af22-e4f85de1cc89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>56f1507d-1eef-43e5-a630-f5395d7d8555</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
