<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Logout</name>
   <tag></tag>
   <elementGuidId>c563fe2a-3e11-4339-9a37-a4de451688bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/nav/div[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Logout&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>05ef16c3-c002-4ee5-8830-c5093f76678a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center space-x-1 py-2 px-3 border border-red-200 hover:border-red-300 text-red-600 hover:bg-red-50 rounded-md transition-colors text-sm font-medium</value>
      <webElementGuid>ffc1193b-2e70-490f-87c3-17913543da41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>dccc08ac-6171-4b0c-9314-7c07f7ed225e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>482c7724-8872-41be-b583-ffc4e7ecf50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;text-text&quot;]/div[@class=&quot;h-screen flex relative&quot;]/div[@class=&quot;flex flex-col flex-grow overflow-auto&quot;]/nav[@class=&quot;navbar border-b border-gray-700 flex items-center justify-between flex-nowrap h-[60px] px-2 sm:px-4 relative&quot;]/div[@class=&quot;hidden md:flex items-center ml-2 sm:ml-4&quot;]/button[@class=&quot;flex items-center space-x-1 py-2 px-3 border border-red-200 hover:border-red-300 text-red-600 hover:bg-red-50 rounded-md transition-colors text-sm font-medium&quot;]</value>
      <webElementGuid>81179e3c-20bb-46ce-81f3-faffa0f00f07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/nav/div[3]/button</value>
      <webElementGuid>9b4bc3b9-2530-46f3-a492-47c8bbdc0425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Refreshed:'])[1]/following::button[1]</value>
      <webElementGuid>b41fe349-9ca6-4dd7-88e0-28bdc497d655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search type'])[1]/following::button[2]</value>
      <webElementGuid>023f8e5c-72c6-4bca-96bf-4254426da933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issues Raised'])[1]/preceding::button[1]</value>
      <webElementGuid>1b0b116e-83fb-4978-bcda-efac009abab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>99beddea-7544-48a8-9b17-2e8d221517c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Logout' and (text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>0fae235a-acd1-4e79-88ac-bac23685f731</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
