<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Rahul Balu Madane_bg-primary hoverbg_0bbdf8</name>
   <tag></tag>
   <elementGuidId>c14bce96-06ab-4711-bf2f-278ef66edef2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div[3]/div/div/div/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Call&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0fb62e56-3f94-4df0-81fb-99f87cd546ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-primary hover:bg-primary/90 transition-colors text-white p-1.5 rounded-full flex items-center justify-center h-7 w-7 shadow-sm</value>
      <webElementGuid>075aea12-a2f4-4675-925d-b246a63b4816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Call</value>
      <webElementGuid>6a3b0ba1-0987-4954-8d0d-612ce6abc525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;text-text&quot;]/div[@class=&quot;h-screen flex relative&quot;]/div[@class=&quot;flex flex-col flex-grow overflow-auto&quot;]/div[@class=&quot;flex-grow overflow-y-auto overflow-x-hidden px-4 py-2 relative&quot;]/div[@class=&quot;p-4 mb-12 md:mb-2&quot;]/div[@class=&quot;w-full grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6&quot;]/div[@class=&quot;relative z-10 bg-white p-5 rounded-[5px] shadow-md border 
                    border-gray-300 flex flex-col cursor-pointer transition-all duration-200&quot;]/div[@class=&quot;border-b border-gray-200 pb-2&quot;]/div[@class=&quot;flex lg:flex-row flex-col-reverse justify-between items-center&quot;]/div[@class=&quot;flex items-center gap-2&quot;]/div[@class=&quot;relative group&quot;]/button[@class=&quot;bg-primary hover:bg-primary/90 transition-colors text-white p-1.5 rounded-full flex items-center justify-center h-7 w-7 shadow-sm&quot;]</value>
      <webElementGuid>7f18c78f-3468-4762-b341-fb1a4cd6f905</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[3]/div/div/div/div/div[2]/button</value>
      <webElementGuid>a72c3cfe-6fac-4fff-bb3d-f864ec5ae6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rahul Balu Madane'])[1]/following::button[2]</value>
      <webElementGuid>d113e177-7e16-4a70-a0a7-060c5cf2740a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Table'])[1]/following::button[2]</value>
      <webElementGuid>efdc5647-2eb3-4182-806d-a523c29f6a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Call Citizen'])[1]/preceding::button[1]</value>
      <webElementGuid>1773963f-606f-4bf2-add6-6198a31028dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View History'])[1]/preceding::button[2]</value>
      <webElementGuid>153f8f95-a197-466e-bc94-6f81a748c88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/button</value>
      <webElementGuid>02cd62b6-cab2-4f3c-94da-eab240f729fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
