<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All DepartmentsAnimal Husbandry Depa_c4d28a</name>
   <tag></tag>
   <elementGuidId>31961a7c-48e7-442d-b008-958fc91e58c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='department']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#department</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Department:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>efb37c67-4bd0-488d-868e-cff5c3f70149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>department</value>
      <webElementGuid>fdc6c0f8-3bc2-4a2b-b453-69903b707486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-600 px-2 md:px-3 py-1 md:py-2 w-full text-sm md:text-base max-w-[180px] md:max-w-[250px] rounded-[5px] truncate</value>
      <webElementGuid>e20c0d3e-5e01-4c5b-aa22-ef0670f49983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All DepartmentsAnimal Husbandry DepartmentFCS(Food and Civil Supplies) DepartmentHealth DepartmentPrimary Education DepartmentWomen and Child Development Department</value>
      <webElementGuid>87233da5-6fa5-48fb-9d66-c7f35a1cec8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;department&quot;)</value>
      <webElementGuid>09646ccb-853e-4559-93bd-2f34fd8a2a90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='department']</value>
      <webElementGuid>8f9dc99c-6dad-4c33-8706-f2146f226662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/select</value>
      <webElementGuid>2c1789e7-c479-49de-a1ce-ea18d97f6d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department:'])[1]/following::select[1]</value>
      <webElementGuid>536c1fab-f3d7-4e74-b888-f28e1e54adb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/following::select[1]</value>
      <webElementGuid>1321cf5e-479f-4fa0-8716-7ef1d222a14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User ID'])[1]/preceding::select[1]</value>
      <webElementGuid>f92eb7a8-9862-41cd-bb17-d5f65f397264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::select[1]</value>
      <webElementGuid>e910740f-1ea3-465e-914d-cc70fe3f91eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>5578e524-02bb-4fbd-b7ab-8616df40d8b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'department' and (text() = 'All DepartmentsAnimal Husbandry DepartmentFCS(Food and Civil Supplies) DepartmentHealth DepartmentPrimary Education DepartmentWomen and Child Development Department' or . = 'All DepartmentsAnimal Husbandry DepartmentFCS(Food and Civil Supplies) DepartmentHealth DepartmentPrimary Education DepartmentWomen and Child Development Department')]</value>
      <webElementGuid>ef0d1a1c-35d7-4872-be41-cdfa56f84264</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
