<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select DepartmentAnimal Husbandry De_46921a</name>
   <tag></tag>
   <elementGuidId>53e6e306-4f3e-4f42-a0db-98ef8f4a3843</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Department']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#department</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Department:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>799d376c-2b29-4d79-b6ba-d9ca1d7f513d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>department</value>
      <webElementGuid>631028b2-bb09-40d4-bc0e-c8d3d07e5feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-600 px-2 md:px-3 py-1 md:py-2 w-full text-sm md:text-base max-w-[180px] md:max-w-[250px] rounded-[5px] truncate</value>
      <webElementGuid>46199d6b-5320-41a9-b0b7-62362a24d090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select DepartmentAnimal Husbandry DepartmentFCS(Food and Civil Supplies) DepartmentHealth DepartmentPrimary Education DepartmentWomen and Child Development Department</value>
      <webElementGuid>056f8db2-41c9-4be0-81df-b87fcf4b223f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;department&quot;)</value>
      <webElementGuid>147f545b-1f8e-4ff4-887a-fe97b2e58d65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='department']</value>
      <webElementGuid>02a9c4a2-0ee9-4d35-bb91-04eda4b6dc93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/select</value>
      <webElementGuid>251a8290-137f-4152-8475-3ef18690b8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department:'])[1]/following::select[1]</value>
      <webElementGuid>e1a098ca-1c70-475f-8a36-1d19e951862d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Whatsapp Issue Report'])[1]/following::select[1]</value>
      <webElementGuid>e8ed6630-8e10-452b-adb9-2514ae414877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaign:'])[1]/preceding::select[1]</value>
      <webElementGuid>e2235881-d618-480a-af09-b7ff7d845d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Initiated'])[1]/preceding::select[2]</value>
      <webElementGuid>8c36a761-fdfc-4605-9d25-363010ff362a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/select</value>
      <webElementGuid>a9ea858d-beed-44fc-9d38-2d6f01a6adbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'department' and (text() = 'Select DepartmentAnimal Husbandry DepartmentFCS(Food and Civil Supplies) DepartmentHealth DepartmentPrimary Education DepartmentWomen and Child Development Department' or . = 'Select DepartmentAnimal Husbandry DepartmentFCS(Food and Civil Supplies) DepartmentHealth DepartmentPrimary Education DepartmentWomen and Child Development Department')]</value>
      <webElementGuid>b5748e49-d2f7-454c-bfd1-a5e924956422</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
