<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_View</name>
   <tag></tag>
   <elementGuidId>724c4440-0f4b-452c-a604-f0cbcb431fc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div[3]/div[2]/table/tbody/tr/td[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;1 View 27125 37782 Open GHUTUKADE PUNDALIK DASHARATH 9765958744 School WhatsApp The conversation begins with a greeting from the S... Neutral 7/16/2025, 7:58:31 PM None None None Huljanti None&quot;i] >> internal:attr=[title=&quot;View full conversation in WhatsApp format&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00d26fcc-ef92-4f7c-9f12-13e330223852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-3 py-1 bg-primary text-white rounded hover:bg-primary-dark flex items-center text-xs transition</value>
      <webElementGuid>19ffa4a9-e1c8-4e27-9915-27d5f3606c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>View full conversation in WhatsApp format</value>
      <webElementGuid>0318eba8-ce99-40f0-ba4c-782a6aac02bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> View</value>
      <webElementGuid>c7dc94b1-301e-4c4a-964c-201c266505bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;text-text&quot;]/div[@class=&quot;h-screen flex relative&quot;]/div[@class=&quot;flex flex-col flex-grow overflow-auto&quot;]/div[@class=&quot;flex-grow overflow-y-auto overflow-x-hidden px-4 py-2 relative&quot;]/div[@class=&quot;p-4 max-w-full overflow-x-auto&quot;]/div[@class=&quot;bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden mb-6&quot;]/div[@class=&quot;overflow-x-auto&quot;]/table[@class=&quot;w-full divide-y divide-gray-200 min-w-max&quot;]/tbody[@class=&quot;bg-white divide-y divide-gray-200&quot;]/tr[@class=&quot;hover:bg-gray-50&quot;]/td[@class=&quot;px-3 py-3 whitespace-nowrap text-sm sticky left-0 bg-white hover:bg-gray-50 z-10&quot;]/div[@class=&quot;flex gap-1&quot;]/button[@class=&quot;px-3 py-1 bg-primary text-white rounded hover:bg-primary-dark flex items-center text-xs transition&quot;]</value>
      <webElementGuid>8f823a5d-d072-409d-9a4d-da7c35a6107d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[3]/div[2]/table/tbody/tr/td[2]/div/button</value>
      <webElementGuid>c14c431e-7e86-4907-b52c-79dff9e7ea3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Village Confirmation'])[1]/following::button[1]</value>
      <webElementGuid>7c2d3930-0ae2-4777-89f2-39fda1f44472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Village'])[2]/following::button[1]</value>
      <webElementGuid>b0c6243e-d61d-41e9-a5b5-4148577297fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/preceding::button[1]</value>
      <webElementGuid>4a2a49e8-e2db-4909-acac-59466e423eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GHUTUKADE PUNDALIK DASHARATH'])[1]/preceding::button[1]</value>
      <webElementGuid>645f4990-36e7-4e5a-8c5d-56d2d6613d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>87325910-8461-49be-9393-046c84bb7568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/button</value>
      <webElementGuid>b629ae28-b7e4-4670-ae19-561eab36ec8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'View full conversation in WhatsApp format' and (text() = ' View' or . = ' View')]</value>
      <webElementGuid>738d7a74-8a76-4e25-b759-398175b5c75f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RINESH AMAR GEJAGE'])[1]/preceding::button[1]</value>
      <webElementGuid>cba46a38-249e-4fc9-9774-1521eda29430</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
