<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Village_css-19bb58m</name>
   <tag></tag>
   <elementGuidId>ee8ba11a-2eb5-4b51-81c4-7ffcfa167656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-hlgwow > div.css-19bb58m</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='village']/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.css-hlgwow > .css-19bb58m</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f93b15f5-1756-4e34-a88f-ee00801f45cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-19bb58m</value>
      <webElementGuid>dbe2a50c-5686-4b8d-9bc5-ef764947ddc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;village&quot;)/div[@class=&quot;css-t3ipsp-control&quot;]/div[@class=&quot;css-hlgwow&quot;]/div[@class=&quot;css-19bb58m&quot;]</value>
      <webElementGuid>994ab920-d892-4ad1-956d-733ca4b47c09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='village']/div/div/div[2]</value>
      <webElementGuid>59ccba14-74d2-4db7-8324-7ccc0f060822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Village'])[1]/following::div[1]</value>
      <webElementGuid>e400b465-a17e-4547-9c48-da6476b85702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Village'])[1]/following::div[5]</value>
      <webElementGuid>72c7e7cb-a52c-4a49-b8b7-1d496a7f4af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agalgaon'])[1]/preceding::div[3]</value>
      <webElementGuid>b54761f2-459d-4cf9-a108-2969032f9737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alipur'])[1]/preceding::div[4]</value>
      <webElementGuid>3fbbf0a0-58d6-4103-8ddb-60c3d859ec93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]</value>
      <webElementGuid>b322c748-b733-4a36-9768-5d3e505fe85f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
