<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select CampaignAnganwadi WhatsAppAni_3e0c5c</name>
   <tag></tag>
   <elementGuidId>4195c24f-c4f1-40e0-82c9-45557ded7b26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#campaign</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='campaign']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Campaign&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6f790433-a36a-4265-b530-e520fb0fc248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>campaign</value>
      <webElementGuid>573cf23d-83ea-49c5-9710-7ad7e447a00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-64 px-3 py-2 text-sm bg-white border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary</value>
      <webElementGuid>b42b6fcf-b060-4429-873e-444d7ae54ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select CampaignAnganwadi WhatsAppAnimal Hospital WhatsAppSchool WhatsAppRation Shop WhatsAppHospital WhatsApp</value>
      <webElementGuid>33c56196-86f7-4d2c-b354-b6ee66409744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;campaign&quot;)</value>
      <webElementGuid>b241265b-6d10-4d02-9314-299e493c8bef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='campaign']</value>
      <webElementGuid>526619b9-1cfc-441d-864c-d500b495b1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>56918052-9eb6-404b-93aa-a5a4f0335cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaign'])[1]/following::select[1]</value>
      <webElementGuid>2cd1722c-d867-47b3-a310-c282b6153dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WhatsApp Confirmation Report'])[1]/following::select[1]</value>
      <webElementGuid>20800449-78ef-4ae6-a961-1bfd7c7441dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Date'])[1]/preceding::select[1]</value>
      <webElementGuid>c86ee8f3-8e6e-4e30-8676-7d45df24c28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Date'])[1]/preceding::select[1]</value>
      <webElementGuid>c5d705da-c755-4953-8fdf-b6b5e0861064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/select</value>
      <webElementGuid>734f8702-5495-4542-9d56-3a1caf60f073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'campaign' and (text() = 'Select CampaignAnganwadi WhatsAppAnimal Hospital WhatsAppSchool WhatsAppRation Shop WhatsAppHospital WhatsApp' or . = 'Select CampaignAnganwadi WhatsAppAnimal Hospital WhatsAppSchool WhatsAppRation Shop WhatsAppHospital WhatsApp')]</value>
      <webElementGuid>e02635fe-c91d-4377-8258-2c95d6a02bfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
