<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select CampaignAnganwadi WhatsAppAni_3e0c5c</name>
   <tag></tag>
   <elementGuidId>4195c24f-c4f1-40e0-82c9-45557ded7b26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#campaign</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='campaign']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Campaign&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e671da00-857a-4734-a84d-4d1df27469d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>campaign</value>
      <webElementGuid>3ecc2c29-c890-419a-9aab-57d8358401a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-64 px-3 py-2 text-sm bg-white border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary</value>
      <webElementGuid>6d054c22-79c3-4049-a1ef-3af194a219b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select CampaignAnganwadi WhatsAppAnimal Hospital WhatsAppSchool WhatsAppRation Shop WhatsAppHospital WhatsApp</value>
      <webElementGuid>b7604e11-45de-4625-93cd-7b83e8729eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;campaign&quot;)</value>
      <webElementGuid>57c93456-3f82-4f42-99fa-71b8098e4e56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='campaign']</value>
      <webElementGuid>4b72c950-2ad7-41cc-a741-8c2ab5c3cab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>e353dba4-3a7f-4aff-998c-7ce01528fba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaign'])[1]/following::select[1]</value>
      <webElementGuid>fa931776-e8f1-4b73-9a61-46fab7374f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WhatsApp Confirmation Report'])[1]/following::select[1]</value>
      <webElementGuid>725e4796-be7a-47fb-a92b-23e07fe453bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Date'])[1]/preceding::select[1]</value>
      <webElementGuid>e986fa64-d7a6-4942-a81d-231106a0e22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Date'])[1]/preceding::select[1]</value>
      <webElementGuid>e7b59506-7aa5-45aa-982b-3778c0aa35b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/select</value>
      <webElementGuid>fde2651e-5c94-49db-88d2-fdc40546659c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'campaign' and (text() = 'Select CampaignAnganwadi WhatsAppAnimal Hospital WhatsAppSchool WhatsAppRation Shop WhatsAppHospital WhatsApp' or . = 'Select CampaignAnganwadi WhatsAppAnimal Hospital WhatsAppSchool WhatsAppRation Shop WhatsAppHospital WhatsApp')]</value>
      <webElementGuid>d151451a-9dff-4fe1-b8a3-3d603f3d190f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
