<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Default (Negative First)Issue Rate (_af6bff</name>
   <tag></tag>
   <elementGuidId>d22e1653-fe00-459c-b18f-855480b15c7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#issueRateSort</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='issueRateSort']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sort By:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bbfc1354-c35f-4c53-802f-b75688e005dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>issueRateSort</value>
      <webElementGuid>d7a18992-5a81-48d1-893d-6d372a1a750a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-400 px-2 py-1 text-sm max-w-[180px] rounded-[5px] truncate</value>
      <webElementGuid>36be6a48-386b-4418-8773-1f697e9f207b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Default (Negative First)Issue Rate (Lowest First)Issue Rate (Highest First)</value>
      <webElementGuid>9f2fddd0-ffff-4e0c-aa54-39bca31b293f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;issueRateSort&quot;)</value>
      <webElementGuid>77ff5937-d5e2-4a8f-a780-0a3b9f3237ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='issueRateSort']</value>
      <webElementGuid>87bc592b-bb10-44a3-b5af-89d1db3ac751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div[4]/select</value>
      <webElementGuid>de117e27-6654-4b49-b447-7ff787c22e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By:'])[1]/following::select[1]</value>
      <webElementGuid>1b309ce5-30bd-4386-be66-48ab68586bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issue:'])[1]/following::select[2]</value>
      <webElementGuid>2ba25ad8-e6d6-46bc-b476-d66bf0608609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Date:'])[1]/preceding::select[1]</value>
      <webElementGuid>423e3da7-771f-4f4a-abf0-d0f1705332ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Date:'])[1]/preceding::select[1]</value>
      <webElementGuid>447a3fc2-1e55-4262-a6c3-93cd94eb02d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>f20fb6aa-342f-43dc-8204-9fc708178390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'issueRateSort' and (text() = 'Default (Negative First)Issue Rate (Lowest First)Issue Rate (Highest First)' or . = 'Default (Negative First)Issue Rate (Lowest First)Issue Rate (Highest First)')]</value>
      <webElementGuid>ac6b5a20-bd70-4e7b-9216-9fe1c2c85e26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
