<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All IssuesAmbulance Service Availabi_6318dd</name>
   <tag></tag>
   <elementGuidId>c313164b-1d2a-4c37-b5da-ad7a36db8243</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#entityFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='entityFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Issue:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>212432a3-9c0d-4f9d-bef0-2e65b33da37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>entityFilter</value>
      <webElementGuid>5c539fce-7e70-4048-bb7c-a08fd09f3c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-400 px-2 py-1 text-sm max-w-[150px] rounded-[5px] truncate</value>
      <webElementGuid>fa7a7c9a-0010-4ba0-821e-9411e361d6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All IssuesAmbulance Service AvailabilityAmbulance Service SatisfactionDoctor AvailabilityMedicine AvailabilityReferral To Private HospitalReferred By Name</value>
      <webElementGuid>1977de34-195f-466f-8b75-200db4b363a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entityFilter&quot;)</value>
      <webElementGuid>747c2311-2295-4088-8610-2ecd6d50dab4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='entityFilter']</value>
      <webElementGuid>8a481e6e-618b-436d-b7c4-8e6b7d5d3ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div[3]/select</value>
      <webElementGuid>a8f0c2d6-e2bf-4708-9d14-228294cce568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issue:'])[1]/following::select[1]</value>
      <webElementGuid>db988972-f3f6-44ef-af52-38f0e6c34af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaign:'])[1]/following::select[2]</value>
      <webElementGuid>b04b5c4c-57dc-42cf-9cb9-20a79c2d8ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By:'])[1]/preceding::select[1]</value>
      <webElementGuid>74cefda4-5aad-4437-929a-c4dd662d089a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Date:'])[1]/preceding::select[2]</value>
      <webElementGuid>28254561-d28e-4383-ac63-5dd7de050e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>83ce4c99-8c1f-41bb-9c37-9863740f68b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'entityFilter' and (text() = 'All IssuesAmbulance Service AvailabilityAmbulance Service SatisfactionDoctor AvailabilityMedicine AvailabilityReferral To Private HospitalReferred By Name' or . = 'All IssuesAmbulance Service AvailabilityAmbulance Service SatisfactionDoctor AvailabilityMedicine AvailabilityReferral To Private HospitalReferred By Name')]</value>
      <webElementGuid>1a35f0c2-930b-44de-8e2b-05cf02416478</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
