<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AllOpenClosed</name>
   <tag></tag>
   <elementGuidId>37398d57-348e-4e4b-9744-bbb8ad1371dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='status']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#status</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Status:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ab8b39f3-df89-4eb5-95d6-1465cb101635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>c9799a3a-1d67-4f22-a78c-f4ced76cf5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-600 px-2 md:px-3 py-1 md:py-2 text-sm md:text-base w-[180px] rounded-[5px] truncate</value>
      <webElementGuid>c6949240-30b9-415b-8dc9-9243c39aa9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllOpenClosed</value>
      <webElementGuid>f201c8aa-982a-4638-b43a-3814f4d88267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status&quot;)</value>
      <webElementGuid>295eb8de-5ce3-4afd-8a9a-f38e7b4d6206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='status']</value>
      <webElementGuid>a1d4fbf5-c275-462d-b32f-8af3e5d45bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div/select</value>
      <webElementGuid>7bbd660c-8d0a-49fe-9982-264dcc4e6b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status:'])[1]/following::select[1]</value>
      <webElementGuid>e2b8680f-a753-4863-9c28-1a1d99660b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issues Raised'])[1]/following::select[1]</value>
      <webElementGuid>3b60a8e8-11d4-4b7b-86a7-8473c2240156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/preceding::select[1]</value>
      <webElementGuid>2e6ed897-7eb7-4210-86cf-1353c5051de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='मराठी'])[1]/preceding::select[1]</value>
      <webElementGuid>e709b731-7a40-4e45-bfa6-e6aa3c3ca356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/select</value>
      <webElementGuid>54a9ea0c-abc3-4031-bd49-58a7d48bc8e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'status' and (text() = 'AllOpenClosed' or . = 'AllOpenClosed')]</value>
      <webElementGuid>ea6925d7-30e5-4c44-9746-0197b2e87367</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
