<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Created At_text-xl</name>
   <tag></tag>
   <elementGuidId>3c7213b4-debf-4173-9f0d-90903e8e85c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Created At'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;2025/05/17/00013 I personally called... - — Call Hanumant Bhanudas Bhale N/A 5/18/2025&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>0c9f82ec-eac8-4f3a-92f4-af37ae407807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>5a8a8769-9474-490c-82ef-da6040837044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>a4917d3c-1735-4b6c-8861-6af1fa3c1436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6ce180fb-7304-4e3c-b3a8-94993415c81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 512 512</value>
      <webElementGuid>f7b225c3-1776-4adc-98c6-f3b55a569262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-xl</value>
      <webElementGuid>e1259cea-9fe8-414b-be15-cc57f724e6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>7c3845b7-81d8-4799-840e-0ae92ce34278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>317688dd-7cfa-4d09-b062-688a901bcf9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>4f83cd31-e3dc-4a02-b10b-1f0fe7427335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;text-text&quot;]/div[@class=&quot;h-screen flex relative&quot;]/div[@class=&quot;flex flex-col flex-grow overflow-auto&quot;]/div[@class=&quot;flex-grow overflow-y-auto overflow-x-hidden px-4 py-2 relative&quot;]/div[@class=&quot;fixed inset-0 bg-black bg-opacity-50 z-40 flex items-center justify-center&quot;]/div[@class=&quot;bg-white p-6 rounded-xl h-max overflow-hidden relative shadow-lg w-[80vw] max-h-[80vh]&quot;]/div[@class=&quot;overflow-x-auto mt-5 rounded-[5px] border shodow-md w-full&quot;]/div[@class=&quot;max-h-[60vh] w-full&quot;]/table[@class=&quot;_rounded_table_qqi9y_1 w-full md:table-fixed table-auto&quot;]/tbody[1]/tr[@class=&quot;bg-gray-500 transition hover:bg-gray-100 border-b border-gray last:border-b-0&quot;]/td[@class=&quot;px-4 py-3 whitespace-pre-wrap text-center&quot;]/button[@class=&quot;text-primary hover:text-green-800 underline&quot;]/svg[@class=&quot;text-xl&quot;]</value>
      <webElementGuid>24b4cfe2-4a1e-4b27-a97d-a49e0a9a8ec7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created At'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>751df329-be45-4a8a-9145-045eaa653740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inv. Officer Name'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>c06371ac-f85c-425d-9f32-fbb9a032b52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I personally called...'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>8a40a4ae-aec4-42b5-94fb-dc34e22bd472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>34dde876-b38e-4d5d-b13f-4279258e074a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
