<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Created At_text-xl</name>
   <tag></tag>
   <elementGuidId>4849b0a4-1387-45a2-92cb-4aa5f0c0235e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Created At'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;2025/05/17/00036 Pashupalakala doctor shi... No Action Needed, — Call Aslam Abdulgani Sayyad N/A 5/28/2025&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>6567aa8d-d5cb-41fd-bcd9-86467ddb484e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>d5d4bf0c-744d-4459-a1f2-cb28eab5f5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>72d46433-b95e-40f3-a1ae-03976aa391d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>edebc27f-0e71-4112-95be-a7b17184aa6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 512 512</value>
      <webElementGuid>e27f0a4d-b557-4fc3-a60a-28d19be2fdab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-xl</value>
      <webElementGuid>0b043772-69cb-4a0f-9cb7-c98c593f8d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>4f8e1147-e666-4adc-acf7-0e3533faefd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>e564c237-5bd0-4214-80fb-1615ec650518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>853ef200-4b53-4a4e-bfb9-eaed7c103546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;text-text&quot;]/div[@class=&quot;h-screen flex relative&quot;]/div[@class=&quot;flex flex-col flex-grow overflow-auto&quot;]/div[@class=&quot;flex-grow overflow-y-auto overflow-x-hidden px-4 py-2 relative&quot;]/div[@class=&quot;fixed inset-0 bg-black bg-opacity-50 z-40 flex items-center justify-center&quot;]/div[@class=&quot;bg-white p-6 rounded-xl h-max overflow-hidden relative shadow-lg w-[80vw] max-h-[80vh]&quot;]/div[@class=&quot;overflow-x-auto mt-5 rounded-[5px] border shodow-md w-full&quot;]/div[@class=&quot;max-h-[60vh] w-full&quot;]/table[@class=&quot;_rounded_table_qqi9y_1 w-full md:table-fixed table-auto&quot;]/tbody[1]/tr[@class=&quot;bg-gray-500 transition hover:bg-gray-100 border-b border-gray last:border-b-0&quot;]/td[@class=&quot;px-4 py-3 whitespace-pre-wrap text-center&quot;]/button[@class=&quot;text-primary hover:text-green-800 underline&quot;]/svg[@class=&quot;text-xl&quot;]</value>
      <webElementGuid>3aa3c455-3acb-4692-8407-f6bef14e6460</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created At'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>9e6ab5fc-e4f3-4b21-8270-8fc1976d1d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inv. Officer Name'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>96295311-544b-471d-8cd3-eb1ab9c47178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pashupalakala doctor shi...'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>37cc2356-2b53-4529-8d3e-f99084a65213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Action Needed,'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>0a52cfcd-01be-4367-b0b3-46c9cb10a5dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
