<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome_w-full bg-gray-50 border bord_29b4f0_1</name>
   <tag></tag>
   <elementGuidId>84122e0b-d6c5-48b1-9fe7-2693cb283181</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Collecto']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Username&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>241d2f06-a86b-493c-8fea-35362d05b25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d96d2a1-bd33-4be8-835e-7d228a0478ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>8ce92831-7c21-4ec3-a3c7-2f96ef3d40ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full bg-gray-50 border border-gray-300 rounded-lg pl-10 pr-4 py-3 text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 focus:bg-white transition duration-200 shadow-sm</value>
      <webElementGuid>ff67cadd-69ca-441b-a315-72ebab429714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Collecto</value>
      <webElementGuid>0b442100-b606-4e19-bcaa-3e2d8daae0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;text-text&quot;]/div[@class=&quot;min-h-screen text-primary relative overflow-hidden flex items-center justify-center p-4 bg-gray-50&quot;]/div[@class=&quot;container mx-auto relative z-10 h-max&quot;]/div[@class=&quot;flex flex-col md:flex-row max-w-4xl mx-auto bg-white shadow-2xl shadow-secondary rounded-xl overflow-hidden&quot;]/div[@class=&quot;w-full md:w-1/2 p-4 md:p-10&quot;]/div[1]/form[@class=&quot;space-y-5&quot;]/div[@class=&quot;relative group&quot;]/input[@class=&quot;w-full bg-gray-50 border border-gray-300 rounded-lg pl-10 pr-4 py-3 text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 focus:bg-white transition duration-200 shadow-sm&quot;]</value>
      <webElementGuid>b6544d78-c2c0-49a0-acdd-b95fc4ac997f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Collecto']</value>
      <webElementGuid>ec2f20ae-a7bb-452d-b80a-5735eac98439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div/div[2]/div/form/div/input</value>
      <webElementGuid>774f7839-cffe-4a7a-8781-66a9955c2a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>de0fd082-68da-4c44-a8b2-4e7fbe1e7926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Username']</value>
      <webElementGuid>39c1c601-3c0e-4c88-975a-31168db54c10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
