<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Default (Negative First)Issue Rate (_af6bff</name>
   <tag></tag>
   <elementGuidId>d1ee3db6-9cc5-49ff-ae51-3357d6a60557</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#issueRateSort</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='issueRateSort']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sort By:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8af4db3a-0542-4924-a449-97077ac7d7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>issueRateSort</value>
      <webElementGuid>ff022dd9-6ce4-476e-9f66-750e604a4186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-400 px-2 py-1 text-sm max-w-[180px] rounded-[5px] truncate</value>
      <webElementGuid>32cc6244-a7ee-4fd9-b819-3bdfab49cf4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Default (Negative First)Issue Rate (Lowest First)Issue Rate (Highest First)</value>
      <webElementGuid>df42ea83-4b53-40df-ba9a-e2babbe5fd59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;issueRateSort&quot;)</value>
      <webElementGuid>b00106d6-d5ce-4721-8016-39a11904130b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='issueRateSort']</value>
      <webElementGuid>087a35c7-f6f5-45f0-b9b8-92eab58dfc81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div[4]/select</value>
      <webElementGuid>1a7ef48b-2c6c-4359-ad3a-b4909b314756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By:'])[1]/following::select[1]</value>
      <webElementGuid>8ef9fbe2-53b2-4300-813e-738d174c823d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issue:'])[1]/following::select[2]</value>
      <webElementGuid>712a9e39-32c9-4fdb-8632-592b2e217286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Date:'])[1]/preceding::select[1]</value>
      <webElementGuid>10c70ffd-c4f6-4129-b554-1c43b452cfd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Date:'])[1]/preceding::select[1]</value>
      <webElementGuid>feff0e0f-dc6b-4075-8b4d-67fab0ac25ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>bfb60dbe-0e2f-4e0c-a10f-00e4377dc1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'issueRateSort' and (text() = 'Default (Negative First)Issue Rate (Lowest First)Issue Rate (Highest First)' or . = 'Default (Negative First)Issue Rate (Lowest First)Issue Rate (Highest First)')]</value>
      <webElementGuid>e30a329d-eac4-4594-9ea7-7128d985cfcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
