<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All IssuesAmbulance Service Availabi_6318dd</name>
   <tag></tag>
   <elementGuidId>4835494e-6ef3-417c-a816-156ed18c21a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#entityFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='entityFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Issue:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4b2bd411-4b2c-4354-ac27-7884993f4e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>entityFilter</value>
      <webElementGuid>32cd3acd-368c-4997-b44c-83a6bfc2209e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-400 px-2 py-1 text-sm max-w-[150px] rounded-[5px] truncate</value>
      <webElementGuid>5d4e7c48-d7af-4507-a43c-807af5dcbc2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All IssuesAmbulance Service AvailabilityAmbulance Service SatisfactionDoctor AvailabilityMedicine AvailabilityReferral To Private HospitalReferred By Name</value>
      <webElementGuid>e22d16b5-4ed7-440f-9444-648d747ae5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entityFilter&quot;)</value>
      <webElementGuid>45f2ce8a-1e46-4b47-9338-c5a1ca57585a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='entityFilter']</value>
      <webElementGuid>31060597-35f3-4165-9bde-04e2a9f78b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div[3]/select</value>
      <webElementGuid>57dd6122-e060-4224-8815-b237698b2609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issue:'])[1]/following::select[1]</value>
      <webElementGuid>6e7df69c-275c-4154-bcdb-03d428d2de06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaign:'])[1]/following::select[2]</value>
      <webElementGuid>63f020d4-f936-4a28-90c8-17e99b0b31c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By:'])[1]/preceding::select[1]</value>
      <webElementGuid>01e19b8b-90d2-4668-a6c6-2cc0e7738a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Date:'])[1]/preceding::select[2]</value>
      <webElementGuid>171d6a6e-c775-4ca8-9699-9d6cbac4efe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>31f95133-12a2-4cea-83ed-81b351989bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'entityFilter' and (text() = 'All IssuesAmbulance Service AvailabilityAmbulance Service SatisfactionDoctor AvailabilityMedicine AvailabilityReferral To Private HospitalReferred By Name' or . = 'All IssuesAmbulance Service AvailabilityAmbulance Service SatisfactionDoctor AvailabilityMedicine AvailabilityReferral To Private HospitalReferred By Name')]</value>
      <webElementGuid>0664348f-cef7-4e13-9bc1-84f6e956a937</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
