<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select DepartmentAnimal Husbandry De_46921a</name>
   <tag></tag>
   <elementGuidId>a3ae1b3e-4a1c-4e05-83f6-59ed6382a0f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='department']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#department</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Department:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3e1117a2-fb19-4a01-a171-801755b7af8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>department</value>
      <webElementGuid>c18b9e54-0fc7-4c0b-a102-3d24ca125c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-300 px-2 md:px-3 py-1 md:py-2 w-full text-sm md:text-base max-w-[180px] md:max-w-[250px] rounded-[5px] truncate</value>
      <webElementGuid>e72f52c6-15a4-4287-b6f8-37e55b1671ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select DepartmentAnimal Husbandry DepartmentFCS(Food and Civil Supplies) DepartmentHealth DepartmentPrimary Education DepartmentWomen and Child Development Department</value>
      <webElementGuid>460f1316-6d12-40e1-8e28-fe063666b169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;department&quot;)</value>
      <webElementGuid>734541b4-4c0f-4e4a-90d2-269c9eaf93b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='department']</value>
      <webElementGuid>0b2a4333-903a-426c-81b3-53b6623274c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/select</value>
      <webElementGuid>32e62f36-655e-45fd-93d6-4d131f89ff6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department:'])[1]/following::select[1]</value>
      <webElementGuid>3b400e99-8c4d-4f08-bda0-cde313b45d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/following::select[1]</value>
      <webElementGuid>6586e101-c80a-4daa-999b-9bb67d3bce7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaign:'])[1]/preceding::select[1]</value>
      <webElementGuid>64f9722d-9ed8-437c-ae6f-8692ccd17664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created By :'])[1]/preceding::select[2]</value>
      <webElementGuid>a8e97f58-8979-4b59-b639-a1acd2d975a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>1b85152f-512d-4d86-8d37-27637eaed5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'department' and (text() = 'Select DepartmentAnimal Husbandry DepartmentFCS(Food and Civil Supplies) DepartmentHealth DepartmentPrimary Education DepartmentWomen and Child Development Department' or . = 'Select DepartmentAnimal Husbandry DepartmentFCS(Food and Civil Supplies) DepartmentHealth DepartmentPrimary Education DepartmentWomen and Child Development Department')]</value>
      <webElementGuid>0575a30e-2ed1-4307-80ad-5b96a5eb705e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
