<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select CampaignHealth CampaignPuravt_181fca</name>
   <tag></tag>
   <elementGuidId>c8c1fe0d-4ce7-4fee-9d1b-5291e0424691</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='campaign']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#campaign</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Campaign&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>733ac196-1b09-45d7-9388-efb5291f99e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>campaign</value>
      <webElementGuid>0162c0e6-1e62-4f9d-b53e-637231cffe58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-64 px-3 py-2 text-sm bg-white border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary</value>
      <webElementGuid>5ca18019-7aaf-4c9c-9167-c47719584f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select CampaignHealth CampaignPuravtha CampaignAnganwadi CampaignSchool CampaignAnimal Health Campaign</value>
      <webElementGuid>2c1dcce3-8275-473f-8f9a-7190634d13d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;campaign&quot;)</value>
      <webElementGuid>ff5bcc8d-fcb2-4742-8b16-e0b1d925483b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='campaign']</value>
      <webElementGuid>ef1a7e0c-8c1a-41e0-aa87-17ac3b1165b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>cbeeec32-527b-4c75-bb62-6126b73a3021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaign'])[1]/following::select[1]</value>
      <webElementGuid>b314c49e-e5b6-4a68-afd5-faf10492ff2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Call Attempt Reports'])[1]/following::select[1]</value>
      <webElementGuid>41d7e721-a54c-4cd4-9102-20f287c38904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Call Attempts'])[1]/preceding::select[1]</value>
      <webElementGuid>e680a4ae-a7d3-457b-85fa-09d5df29687b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/select</value>
      <webElementGuid>725da788-65cf-423b-a522-a3151308ba62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'campaign' and (text() = 'Select CampaignHealth CampaignPuravtha CampaignAnganwadi CampaignSchool CampaignAnimal Health Campaign' or . = 'Select CampaignHealth CampaignPuravtha CampaignAnganwadi CampaignSchool CampaignAnimal Health Campaign')]</value>
      <webElementGuid>9347f302-a0aa-48ea-9372-989b8c500cb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
