<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome_w-full bg-gray-50 border bord_c3e347_1_2_3</name>
   <tag></tag>
   <elementGuidId>a29fa20b-adee-473c-9c67-d885877e0f14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='i']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9dcd20ba-19de-451a-9855-34d913c2ac1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9a7571cd-11ad-4d76-8d71-7e0a36caabad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>42d5c680-2943-4733-ad4f-d39ab7f860a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full bg-gray-50 border border-gray-300 rounded-lg pl-10 pr-10 py-3 text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 focus:bg-white transition duration-200 shadow-sm</value>
      <webElementGuid>58c99824-9f29-4938-9298-06ffc388e792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5d2cce97-45e9-4ca1-8f4d-cc0126ff88cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;text-text&quot;]/div[@class=&quot;min-h-screen text-primary relative overflow-hidden flex items-center justify-center p-4 bg-gray-50&quot;]/div[@class=&quot;container mx-auto relative z-10 h-max&quot;]/div[@class=&quot;flex flex-col md:flex-row max-w-4xl mx-auto bg-white shadow-2xl shadow-secondary rounded-xl overflow-hidden&quot;]/div[@class=&quot;w-full md:w-1/2 p-4 md:p-10&quot;]/div[1]/form[@class=&quot;space-y-5&quot;]/div[@class=&quot;relative group&quot;]/input[@class=&quot;w-full bg-gray-50 border border-gray-300 rounded-lg pl-10 pr-10 py-3 text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 focus:bg-white transition duration-200 shadow-sm&quot;]</value>
      <webElementGuid>d9aee9f0-d6b5-4cad-bd38-d77c8765d621</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='i']</value>
      <webElementGuid>a8e63507-ba30-4f8a-9b51-2c97f24830f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div/div[2]/div/form/div[2]/input</value>
      <webElementGuid>9648e9e3-a38c-4bc0-9226-376c79f7761c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>c7654872-4f9c-4cab-9b36-38962a855919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>34f2c270-61e7-49f2-8176-360b28284a23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
