<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select DepartmentAnimal Husbandry De_46921a</name>
   <tag></tag>
   <elementGuidId>6270f544-6bdc-417a-9572-88cd12a1f3b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='department']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#department</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Department:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3a09a8fa-d67c-478b-9b5d-65a660d9a6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>department</value>
      <webElementGuid>3dbdf4f7-7519-45b4-8046-21391ac17642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-600 px-2 md:px-3 py-1 md:py-2 w-full text-sm md:text-base max-w-[180px] md:max-w-[250px] rounded-[5px] truncate</value>
      <webElementGuid>c9b96671-a21a-4105-a675-2eb2b9915b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select DepartmentAnimal Husbandry DepartmentFCS(Food and Civil Supplies) DepartmentHealth DepartmentPrimary Education DepartmentWomen and Child Development Department</value>
      <webElementGuid>3f0147a0-6a89-4ccf-9d78-7da603b1a093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;department&quot;)</value>
      <webElementGuid>e0f14dca-0998-4be1-a6fb-a5975e1f1c26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='department']</value>
      <webElementGuid>4b73159e-d4e9-48d7-a440-c3c1c3215de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div/div/select</value>
      <webElementGuid>a62ba603-ad3a-4659-a7a7-f135822b9605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department:'])[1]/following::select[1]</value>
      <webElementGuid>ba0650d5-0da8-4798-ad0f-b5bbfe64da37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::select[1]</value>
      <webElementGuid>6d4c23e8-2869-4ee9-b6b4-17d5be572dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaign:'])[1]/preceding::select[1]</value>
      <webElementGuid>45186f98-2af8-4311-aca7-4b5ea73d15f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Date:'])[1]/preceding::select[2]</value>
      <webElementGuid>6f21e186-afa1-45eb-a99c-6dfaaaeea5eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/select</value>
      <webElementGuid>01c4441c-4906-45ed-859a-2c4f3284bfd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'department' and (text() = 'Select DepartmentAnimal Husbandry DepartmentFCS(Food and Civil Supplies) DepartmentHealth DepartmentPrimary Education DepartmentWomen and Child Development Department' or . = 'Select DepartmentAnimal Husbandry DepartmentFCS(Food and Civil Supplies) DepartmentHealth DepartmentPrimary Education DepartmentWomen and Child Development Department')]</value>
      <webElementGuid>6955acbd-49ed-4222-be59-535296529b5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
