<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Default (Negative First)Issue Rate (_af6bff</name>
   <tag></tag>
   <elementGuidId>e638d76e-fe15-4182-b233-d52517ed6dfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='issueRateSort']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#issueRateSort</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sort By:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a825f5e8-e5d5-4382-adb4-fe0d71e54a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>issueRateSort</value>
      <webElementGuid>7aa035be-de01-42da-b080-f5c9f52cd5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-400 px-2 py-1 text-sm max-w-[180px] rounded-[5px] truncate</value>
      <webElementGuid>2a306c16-b625-4f87-8437-d4ff6d210b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Default (Negative First)Issue Rate (Lowest First)Issue Rate (Highest First)</value>
      <webElementGuid>3e0c2e7c-b3c7-45fa-827f-e83013341fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;issueRateSort&quot;)</value>
      <webElementGuid>6e66be1f-d46b-4b7d-9995-5bbecdb69623</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='issueRateSort']</value>
      <webElementGuid>a28db6fd-c7da-477c-9de9-9139ad462483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div[4]/select</value>
      <webElementGuid>5dc62f09-69c2-4e58-a0d4-9561edcb7b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By:'])[1]/following::select[1]</value>
      <webElementGuid>1e585752-c46a-4d8f-9132-45d7a9a9991f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issue:'])[1]/following::select[2]</value>
      <webElementGuid>dc5ebb82-a803-4084-b2b1-d6d84b12d475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Date:'])[1]/preceding::select[1]</value>
      <webElementGuid>78fb0994-e589-4315-b6b4-b7dbf88af80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Date:'])[1]/preceding::select[1]</value>
      <webElementGuid>c3ed0fd3-4be1-4c84-b089-8a25dad35e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>b1d441ac-0594-481c-92fb-7a2dc65477c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'issueRateSort' and (text() = 'Default (Negative First)Issue Rate (Lowest First)Issue Rate (Highest First)' or . = 'Default (Negative First)Issue Rate (Lowest First)Issue Rate (Highest First)')]</value>
      <webElementGuid>5c947b4f-6aeb-46c2-aa1b-390688882ef6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
