<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All IssuesAmbulance Service Availabi_6318dd</name>
   <tag></tag>
   <elementGuidId>7ecf1bd4-cdc9-45a1-a41f-4c07a0928ed0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='entityFilter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#entityFilter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Issue:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2142039a-957e-4584-afd6-70d7a2eb4b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>entityFilter</value>
      <webElementGuid>4bee19f2-12b4-43c6-b26b-9ce5e8dd4713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-400 px-2 py-1 text-sm max-w-[150px] rounded-[5px] truncate</value>
      <webElementGuid>584f7964-bda3-4792-815b-e37348aafd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All IssuesAmbulance Service AvailabilityAmbulance Service SatisfactionDoctor AvailabilityMedicine AvailabilityReferral To Private HospitalReferred By Name</value>
      <webElementGuid>da985bac-9302-474c-8b1b-562e8bc183d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entityFilter&quot;)</value>
      <webElementGuid>a727dc35-dba8-4bea-bbb3-648056bbde9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='entityFilter']</value>
      <webElementGuid>e170e70f-3050-4249-b3f3-c0aa3fca0e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div[3]/select</value>
      <webElementGuid>369eff76-cffd-4884-9d63-d8d38fb29e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issue:'])[1]/following::select[1]</value>
      <webElementGuid>205905b6-46fe-4eae-b107-6eb50d4f650e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaign:'])[1]/following::select[2]</value>
      <webElementGuid>dafeeb6b-2b0c-4b5c-abc2-b0a7b1349dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By:'])[1]/preceding::select[1]</value>
      <webElementGuid>5a633321-a0f4-4473-8447-118639f7ee50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Date:'])[1]/preceding::select[2]</value>
      <webElementGuid>8ba17933-5bed-47b0-be7d-93319ddab3c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>672755ed-7a92-4625-a742-c3f00c255e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'entityFilter' and (text() = 'All IssuesAmbulance Service AvailabilityAmbulance Service SatisfactionDoctor AvailabilityMedicine AvailabilityReferral To Private HospitalReferred By Name' or . = 'All IssuesAmbulance Service AvailabilityAmbulance Service SatisfactionDoctor AvailabilityMedicine AvailabilityReferral To Private HospitalReferred By Name')]</value>
      <webElementGuid>29d8f2a0-4878-4d2a-b8d2-3ad562307b29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
