<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ranjeet Uddhavraj Jadhav</name>
   <tag></tag>
   <elementGuidId>1c331ced-e447-4c77-b80b-070582b29309</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Hanumant Bhanudas Bhale'])[1]/preceding::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-4-option-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Ranjeet Uddhavraj Jadhav&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>28b68f44-f7f5-48c2-a7fe-c5b384839b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-d7l1ni-option</value>
      <webElementGuid>59032544-3eca-4ff9-8d2c-a1500bb66b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>82fa9cc2-4c8c-4558-b25a-c23e0a00798a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-4-option-4</value>
      <webElementGuid>981b26e8-c1c0-4f33-9ef2-019648939285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8cb8c730-faa9-4c5a-9372-3375aa36ca75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>32489e7a-87fc-46e9-a3cd-ea1eca384d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c2a7f8fa-6f23-41f2-9bc6-fda70f6f3379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ranjeet Uddhavraj Jadhav</value>
      <webElementGuid>3d4d38af-166d-407a-892f-c149ef54acc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-4-option-4&quot;)</value>
      <webElementGuid>f704c2b7-b8d2-4fcd-9343-386d7e112eec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-4-option-4']</value>
      <webElementGuid>1020cb20-ad91-44dc-8fa1-3c42ece093ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-4-listbox']/div[5]</value>
      <webElementGuid>701a7f6b-ce5d-45ce-b7db-d1fd85d6ca32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priyanka Mahendra Jadhav'])[2]/following::div[2]</value>
      <webElementGuid>793aff60-e821-4123-903f-bc38ff1a9b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hanumant Bhanudas Bhale'])[1]/preceding::div[1]</value>
      <webElementGuid>c2fec1be-791d-4ebf-b6c8-593447b61869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vishnu Shripati Kolekar'])[1]/preceding::div[2]</value>
      <webElementGuid>a6d56b76-f3a6-498a-ba93-7257bba93f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ranjeet Uddhavraj Jadhav']/parent::*</value>
      <webElementGuid>6072d714-95a3-40bf-8024-888129444d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]</value>
      <webElementGuid>e0e7ed05-a8be-41ff-913f-4ceddba04d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-4-option-4' and (text() = 'Ranjeet Uddhavraj Jadhav' or . = 'Ranjeet Uddhavraj Jadhav')]</value>
      <webElementGuid>ac12257c-5741-49b6-84b1-a95b03f96ecc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
