<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select DepartmentAnimal Husbandry De_46921a</name>
   <tag></tag>
   <elementGuidId>cf3cc7af-6c50-4ed2-b018-18faa7799255</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#department</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='department']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Department:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ba1904ec-7e59-4f66-bff1-d57a4e480017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>department</value>
      <webElementGuid>4e83c22a-8a60-45e0-8c79-405fc5d24536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-300 px-2 md:px-3 py-1 md:py-2 w-full text-sm md:text-base max-w-[180px] md:max-w-[250px] rounded-[5px] truncate</value>
      <webElementGuid>271dcaf7-e171-4502-a9ee-edfe7413d726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select DepartmentAnimal Husbandry DepartmentFCS(Food and Civil Supplies) DepartmentHealth DepartmentPrimary Education DepartmentWomen and Child Development Department</value>
      <webElementGuid>0b136ba1-6aad-4528-86e4-2333d63f0629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;department&quot;)</value>
      <webElementGuid>f0a01572-6252-411c-8e30-fff8ffb7eb26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='department']</value>
      <webElementGuid>fea40d52-cd68-469c-9288-7eaee5600df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/select</value>
      <webElementGuid>0bf970d2-517f-49e5-a3d1-7b01536058ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department:'])[1]/following::select[1]</value>
      <webElementGuid>acbb877f-4402-4288-8e36-411fc46dacff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/following::select[1]</value>
      <webElementGuid>39efb41e-c636-4da2-8af5-e0f839ca1644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaign:'])[1]/preceding::select[1]</value>
      <webElementGuid>db2107c0-82d3-435d-9ec6-6f40d2290b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created By :'])[1]/preceding::select[2]</value>
      <webElementGuid>fc34c77b-237f-40e8-a985-b1eaa311a35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>4c7290d8-8b1e-4857-b235-6fc95b4e0568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'department' and (text() = 'Select DepartmentAnimal Husbandry DepartmentFCS(Food and Civil Supplies) DepartmentHealth DepartmentPrimary Education DepartmentWomen and Child Development Department' or . = 'Select DepartmentAnimal Husbandry DepartmentFCS(Food and Civil Supplies) DepartmentHealth DepartmentPrimary Education DepartmentWomen and Child Development Department')]</value>
      <webElementGuid>b1557428-1484-497a-bfeb-b460ef289041</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
