<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Created At_text-xl</name>
   <tag></tag>
   <elementGuidId>a953006f-68b3-4e14-bd14-10e236d9acfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Created At'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;2025/07/17/00003 ऑफीस notice issued... Official Notice Issued Call Iqbal Dastgir Shaikh Dr Shaikh I... Madha Anjangaon Umate July 1, 2025&quot;i] >> internal:role=button >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>a9faf357-ac7d-4300-ac18-7fc2968667a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>ebd68ea8-7495-4480-96a6-4d7eef99b607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>db13b395-b3ba-4114-8cc5-31e848c8846a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eb28f74d-1bdd-463c-982a-d4a43fdc139d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 512 512</value>
      <webElementGuid>16b77b96-5db3-43c1-b1bb-4a6e9daf48d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-xl</value>
      <webElementGuid>32f1d5f5-021b-4029-bdbf-0995d53dcc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>384f8aee-bf3c-46ce-97ae-e43e45b818a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>baa0f477-0772-4640-9fdd-c28037afbcb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>0a6eda52-e481-441f-b5c1-88859c354c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;text-text&quot;]/div[@class=&quot;h-screen flex relative&quot;]/div[@class=&quot;flex flex-col flex-grow overflow-auto&quot;]/div[@class=&quot;flex-grow overflow-y-auto overflow-x-hidden px-4 py-2 relative&quot;]/div[@class=&quot;mt-2 mb-4 pb-8&quot;]/div[@class=&quot;overflow-x-auto mt-2 rounded-[5px] border border-gray-400 shodow-md&quot;]/table[@class=&quot;_rounded_table_qqi9y_1 w-full md:table-fixed table-auto h-[460px]&quot;]/tbody[@class=&quot;oveerflow-y-scroll&quot;]/tr[@class=&quot;hover:bg-gray-100 cursor-pointer&quot;]/td[@class=&quot;text-center text-[14px] p-2&quot;]/button[@class=&quot;text-primary hover:text-green-800 underline&quot;]/svg[@class=&quot;text-xl&quot;]</value>
      <webElementGuid>75e2ad77-647c-48b6-b7af-621b18d8650c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created At'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>670d76f5-e50f-41f7-8bf9-77f1ab005556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Village'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>c420c496-1f8a-48e6-9082-6631d8f7b701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ऑफीस notice issued...'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>29090fb3-3065-4e28-a1e8-2323d1fdddf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Official Notice Issued'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>04076cef-65c0-4523-9078-c406559c30ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
