<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search type_flex-grow px-4 py-1 outline-none_1_2_3</name>
   <tag></tag>
   <elementGuidId>ee8759f4-15d0-4b58-b7c9-d26082496c6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.flex-grow.px-4.py-1.outline-none</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='429122']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6c30886-3ec8-4ed8-839d-d67d3ec5f382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3859ce30-3ce4-441d-b69b-105966abe9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>28d57de9-83aa-4f9f-8942-575101c245c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-grow px-4 py-1 outline-none</value>
      <webElementGuid>acda4e4e-cdda-4a2a-a7b5-435bf14f3b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>429122</value>
      <webElementGuid>48399738-a64f-4ea4-b1e4-e1e939f9a416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;text-text&quot;]/div[@class=&quot;h-screen flex relative&quot;]/div[@class=&quot;flex flex-col flex-grow overflow-auto&quot;]/nav[@class=&quot;navbar border-b border-gray-700 flex items-center justify-between flex-nowrap h-[60px] px-2 sm:px-4 relative&quot;]/form[@class=&quot;w-full flex justify-center items-center relative&quot;]/div[@class=&quot;hidden md:flex rounded-lg border border-gray-300 overflow-hidden&quot;]/div[@class=&quot;flex items-center&quot;]/input[@class=&quot;flex-grow px-4 py-1 outline-none&quot;]</value>
      <webElementGuid>9696a2a7-79bd-4858-b5d3-72feaa3e9758</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='429122']</value>
      <webElementGuid>782c2248-7d64-4949-b3bd-b1e818ca0a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/nav/form/div[2]/div/input</value>
      <webElementGuid>96cbf73e-5c1a-4cfc-af00-653a2156c67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>589382b1-ea45-4e56-8cb3-acef12207dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search...']</value>
      <webElementGuid>4368fcf3-7045-4aaf-ad91-a23502ad6328</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
