<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search type_flex-grow px-4 py-1 outline-none_1</name>
   <tag></tag>
   <elementGuidId>2298cc1e-7b8b-4548-a1a5-36994bcd7839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.flex-grow.px-4.py-1.outline-none</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='83520']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dad8d792-8953-497c-a46a-d6922f70e583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e38ac1ae-e6bb-431c-8696-e6c9a56446d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>a4a2e6aa-5590-483c-aac3-ec97a72ec7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-grow px-4 py-1 outline-none</value>
      <webElementGuid>9643c3fb-8018-4a8a-924c-bef628e3cfdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>83520</value>
      <webElementGuid>3dcf2690-a38a-4f59-a6b0-e12a4745ee51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;text-text&quot;]/div[@class=&quot;h-screen flex relative&quot;]/div[@class=&quot;flex flex-col flex-grow overflow-auto&quot;]/nav[@class=&quot;navbar border-b border-gray-700 flex items-center justify-between flex-nowrap h-[60px] px-2 sm:px-4 relative&quot;]/form[@class=&quot;w-full flex justify-center items-center relative&quot;]/div[@class=&quot;hidden md:flex rounded-lg border border-gray-300 overflow-hidden&quot;]/div[@class=&quot;flex items-center&quot;]/input[@class=&quot;flex-grow px-4 py-1 outline-none&quot;]</value>
      <webElementGuid>e9cac870-3e9c-45ea-84f7-05128a45ccd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='83520']</value>
      <webElementGuid>359d6446-758a-4982-ad42-744497f71555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/nav/form/div[2]/div/input</value>
      <webElementGuid>8ba54fe9-9390-4380-93d6-10b87d3021ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f1b63f61-9a22-410e-9d81-3a19ae056ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search...']</value>
      <webElementGuid>3b332cc9-4964-4282-be2a-1ce95e86e0de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
