<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Issue IDCitizen ID</name>
   <tag></tag>
   <elementGuidId>fa807dca-e3d3-479d-a7a7-a3a0ceecda62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dashboard-search-type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dashboard-search-type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Search type&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>19eaa6c7-0a0a-4d1d-a3b6-d8c7fbadd48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dashboard-search-type</value>
      <webElementGuid>a8605fa2-10a6-4d83-84d0-4d94beebcf1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-r border-gray-300 outline-none px-2</value>
      <webElementGuid>c2bef12d-170e-4418-b7c5-1126b11d74b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Issue IDCitizen ID</value>
      <webElementGuid>910454e4-95d4-4026-8afc-d69e26ddcb74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard-search-type&quot;)</value>
      <webElementGuid>b6893c5b-d222-4b66-b01d-ef7be6b045e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dashboard-search-type']</value>
      <webElementGuid>eb4cafbb-fa64-43fe-b568-6531fa323c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/nav/form/div[2]/select</value>
      <webElementGuid>b752116e-dd4d-40c0-959a-692241656c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search type'])[1]/following::select[1]</value>
      <webElementGuid>f316eadd-b997-4cdc-b6c5-8deadfeb65f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AI Citizen Engagement Solution'])[1]/following::select[1]</value>
      <webElementGuid>d1249274-b5a1-45ab-96a4-c599f6ff8187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Refreshed:'])[1]/preceding::select[1]</value>
      <webElementGuid>b269e305-9292-445c-9cfb-798300410445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::select[1]</value>
      <webElementGuid>b6d8023f-1088-42b1-a02c-9974bac48ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c1a36a0e-eb0a-4e23-8c1a-979352a43bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dashboard-search-type' and (text() = 'Issue IDCitizen ID' or . = 'Issue IDCitizen ID')]</value>
      <webElementGuid>7ba46b42-2215-4b22-bcbc-e6b800ca7cae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
