<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome_w-full bg-gray-50 border bord_29b4f0_1_2</name>
   <tag></tag>
   <elementGuidId>7b8e1943-f2b8-4d84-9134-f2b2fabf2f07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Collectoe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Username&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d67b0dd-cc98-4331-a901-56962bf7dad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd28e64b-dabb-4388-839a-16ba4959e2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>58273023-ac09-4ac0-a0c4-2fe156f430e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full bg-gray-50 border border-gray-300 rounded-lg pl-10 pr-4 py-3 text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 focus:bg-white transition duration-200 shadow-sm</value>
      <webElementGuid>4d49d288-2955-4f4f-8fd2-a4e80fd2200e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Collectoe</value>
      <webElementGuid>f08b5523-ac34-46c6-8a44-ed94bcf83ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;text-text&quot;]/div[@class=&quot;min-h-screen text-primary relative overflow-hidden flex items-center justify-center p-4 bg-gray-50&quot;]/div[@class=&quot;container mx-auto relative z-10 h-max&quot;]/div[@class=&quot;flex flex-col md:flex-row max-w-4xl mx-auto bg-white shadow-2xl shadow-secondary rounded-xl overflow-hidden&quot;]/div[@class=&quot;w-full md:w-1/2 p-4 md:p-10&quot;]/div[1]/form[@class=&quot;space-y-5&quot;]/div[@class=&quot;relative group&quot;]/input[@class=&quot;w-full bg-gray-50 border border-gray-300 rounded-lg pl-10 pr-4 py-3 text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 focus:bg-white transition duration-200 shadow-sm&quot;]</value>
      <webElementGuid>0a96bfef-b6e4-4144-8d9d-68198793462b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Collectoe']</value>
      <webElementGuid>4f90bdfd-00d0-4775-9896-677a00c081cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div/div[2]/div/form/div/input</value>
      <webElementGuid>96ce655f-7aab-4025-b01d-f8fbd76331f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>306144bf-cbcc-4836-98a2-93856d946a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Username']</value>
      <webElementGuid>4293ac5a-6e01-4345-917f-0387bc1362c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
